// ── GO rail line registry ─────────────────────────────────
// Display metadata is hand-authored here; everything else (station list,
// order, names, railsix slugs, schedules) comes from the per-line JSON files
// generated by scripts/generate-schedule.mjs from the official GO GTFS feed.

import ST from '@/data/schedules/ST.json';
import LW from '@/data/schedules/LW.json';
import LE from '@/data/schedules/LE.json';
import BR from '@/data/schedules/BR.json';
import RH from '@/data/schedules/RH.json';
import KI from '@/data/schedules/KI.json';
import MI from '@/data/schedules/MI.json';

export interface StationInfo {
  code: string;        // GTFS stop_id, e.g. "UI"
  name: string;        // "Unionville GO"
  shortName: string;   // "Unionville"
  railsixSlug: string; // railsix.com route URL slug
}

export interface GtfsTrip {
  tripId: string;
  vehicleType: 'train' | 'bus';
  stopTimes: Record<string, string>; // stationCode → "HH:MM"
}

export interface LineSchedule {
  id: string;
  effectiveDate: string;
  stations: StationInfo[]; // outward → Union (last entry is Union Station)
  weekday: { toUnion: GtfsTrip[]; fromUnion: GtfsTrip[] };
  saturday: { toUnion: GtfsTrip[]; fromUnion: GtfsTrip[] };
  sunday: { toUnion: GtfsTrip[]; fromUnion: GtfsTrip[] };
}

// Per-line schedule data, keyed by line id.
const SCHEDULES: Record<string, LineSchedule> = {
  ST: ST as unknown as LineSchedule,
  LW: LW as unknown as LineSchedule,
  LE: LE as unknown as LineSchedule,
  BR: BR as unknown as LineSchedule,
  RH: RH as unknown as LineSchedule,
  KI: KI as unknown as LineSchedule,
  MI: MI as unknown as LineSchedule,
};

export const UNION_CODE = 'UN';

interface LineMeta {
  id: string;
  name: string;        // "Stouffville Line"
  shortName: string;   // "Stouffville"
  color: string;       // official GO line colour (used for the line badge)
  defaultHomeCode?: string; // overrides the terminus default
}

// Hand-authored display metadata + official GO line colours.
// Order here is the order shown in the line picker.
const LINE_META: LineMeta[] = [
  { id: 'LW', name: 'Lakeshore West', shortName: 'Lakeshore W', color: '#98002e', defaultHomeCode: 'OA' },
  { id: 'LE', name: 'Lakeshore East', shortName: 'Lakeshore E', color: '#ff0d00', defaultHomeCode: 'WH' },
  { id: 'ST', name: 'Stouffville',    shortName: 'Stouffville', color: '#794500', defaultHomeCode: 'UI' },
  { id: 'RH', name: 'Richmond Hill',  shortName: 'Richmond Hill', color: '#0099c7' },
  { id: 'BR', name: 'Barrie',         shortName: 'Barrie',      color: '#003767', defaultHomeCode: 'AU' },
  { id: 'KI', name: 'Kitchener',      shortName: 'Kitchener',   color: '#00853e', defaultHomeCode: 'BE' },
  { id: 'MI', name: 'Milton',         shortName: 'Milton',      color: '#f57f25' },
];

export interface LineInfo extends LineMeta {
  effectiveDate: string;
  stations: StationInfo[];      // full line, outward → Union
  homeStations: StationInfo[];  // selectable home stations (excludes Union)
  defaultHomeCode: string;      // resolved
}

export const LINES: LineInfo[] = LINE_META.map((meta) => {
  const sched = SCHEDULES[meta.id];
  const homeStations = sched.stations.filter((s) => s.code !== UNION_CODE);
  const fallback = homeStations[0]?.code ?? UNION_CODE;
  return {
    ...meta,
    effectiveDate: sched.effectiveDate,
    stations: sched.stations,
    homeStations,
    defaultHomeCode:
      meta.defaultHomeCode && homeStations.some((s) => s.code === meta.defaultHomeCode)
        ? meta.defaultHomeCode
        : fallback,
  };
});

export const DEFAULT_LINE_ID = 'ST';

export function getLine(id: string): LineInfo {
  return LINES.find((l) => l.id === id) ?? LINES.find((l) => l.id === DEFAULT_LINE_ID)!;
}

export function getLineSchedule(id: string): LineSchedule {
  return SCHEDULES[id] ?? SCHEDULES[DEFAULT_LINE_ID];
}

export function getStation(lineId: string, code: string): StationInfo {
  const line = getLine(lineId);
  return line.stations.find((s) => s.code === code)
    ?? line.homeStations.find((s) => s.code === line.defaultHomeCode)
    ?? line.stations[0];
}
