// ── Station config ────────────────────────────────────────

export interface StationInfo {
  name: string;         // "Unionville GO"
  shortName: string;    // "Unionville"
  code: string;         // GTFS stop_id, e.g. "UI"
  railsixSlug: string;  // railsix.com route URL slug
}

// All Stouffville line home stations (excludes Union Station which is always the office)
// Ordered north → south (Old Elm end → Toronto end), matching GTFS stop_ids
export const STOUFFVILLE_HOME_STATIONS: StationInfo[] = [
  { name: 'Old Elm GO',     shortName: 'Old Elm',     code: 'LI', railsixSlug: 'old-elm'     },
  { name: 'Stouffville GO', shortName: 'Stouffville', code: 'ST', railsixSlug: 'stouffville' },
  { name: 'Mount Joy GO',   shortName: 'Mount Joy',   code: 'MJ', railsixSlug: 'mount-joy'   },
  { name: 'Markham GO',     shortName: 'Markham',     code: 'MR', railsixSlug: 'markham'     },
  { name: 'Centennial GO',  shortName: 'Centennial',  code: 'CE', railsixSlug: 'centennial'  },
  { name: 'Unionville GO',  shortName: 'Unionville',  code: 'UI', railsixSlug: 'unionville'  },
  { name: 'Milliken GO',    shortName: 'Milliken',    code: 'MK', railsixSlug: 'milliken'    },
  { name: 'Agincourt GO',   shortName: 'Agincourt',   code: 'AG', railsixSlug: 'agincourt'   },
  { name: 'Kennedy GO',     shortName: 'Kennedy',     code: 'KE', railsixSlug: 'kennedy'     },
];

export const DEFAULT_HOME_STATION_CODE = 'UI';

export function getStationByCode(code: string): StationInfo {
  return STOUFFVILLE_HOME_STATIONS.find((s) => s.code === code) ?? STOUFFVILLE_HOME_STATIONS[5]; // fallback UI
}

// ── Trip types ────────────────────────────────────────────

export interface Trip {
  departure: string;              // "HH:MM" from origin (home station SB, Union NB)
  arrival: string;                // "HH:MM" at destination (Union SB, home station NB)
  tripTime: string;               // "N min"
  vehicleType: 'train' | 'bus';
  tripId: string;                 // GTFS trip_id
  stopTimes: Record<string, string>; // stationCode → "HH:MM" for all stops in this trip
}

export type ServiceType = 'weekday' | 'saturday' | 'sunday';
export type Direction = 'homeToOffice' | 'officeToHome';

// ── GTFS schedule data ────────────────────────────────────
// Generated by scripts/generate-schedule.mjs from the official GO Transit GTFS feed.
// To refresh: node scripts/generate-schedule.mjs

import rawSchedule from '@/data/stouffville-schedule.json';

interface GtfsTrip {
  tripId: string;
  vehicleType: 'train' | 'bus';
  stopTimes: Record<string, string>;
}

interface GtfsSchedule {
  effectiveDate: string;
  weekday: { sb: GtfsTrip[]; nb: GtfsTrip[] };
  saturday: { sb: GtfsTrip[]; nb: GtfsTrip[] };
  sunday: { sb: GtfsTrip[]; nb: GtfsTrip[] };
}

const schedule = rawSchedule as GtfsSchedule;

export const SCHEDULE_EFFECTIVE_DATE = schedule.effectiveDate;

// Stouffville line stop order: north → south (SB = toward Union)
const SB_ORDER = ['LI', 'ST', 'MJ', 'MR', 'CE', 'UI', 'MK', 'AG', 'KE', 'UN'];
const NB_ORDER = [...SB_ORDER].reverse();

// Full stop name lookup (for display in stop sequences)
const STOP_NAMES: Record<string, string> = {
  LI: 'Old Elm GO',
  ST: 'Stouffville GO',
  MJ: 'Mount Joy GO',
  MR: 'Markham GO',
  CE: 'Centennial GO',
  UI: 'Unionville GO',
  MK: 'Milliken GO',
  AG: 'Agincourt GO',
  KE: 'Kennedy GO',
  UN: 'Union Station',
};

// Name → code mapping for live stop name resolution (from railsix)
const STOP_CODE_MAP: Record<string, string> = {
  'old elm':      'LI',
  'stouffville':  'ST',
  'mount joy':    'MJ',
  'markham':      'MR',
  'centennial':   'CE',
  'unionville':   'UI',
  'milliken':     'MK',
  'agincourt':    'AG',
  'kennedy':      'KE',
  'union station':'UN',
  'union':        'UN',
};

// ── Schedule lookup ───────────────────────────────────────

/**
 * Returns all trips for a given station, direction, and service type from
 * the GTFS schedule. All stations are treated equally — no hardcoded data.
 */
export function getScheduleForStation(
  direction: Direction,
  serviceType: ServiceType,
  stationCode: string,
): Trip[] {
  const dayTrips = direction === 'homeToOffice'
    ? schedule[serviceType].sb
    : schedule[serviceType].nb;

  return dayTrips
    .filter((t) => stationCode in t.stopTimes && 'UN' in t.stopTimes)
    .map((t) => {
      const departure = direction === 'homeToOffice'
        ? t.stopTimes[stationCode]
        : t.stopTimes['UN'];
      const arrival = direction === 'homeToOffice'
        ? t.stopTimes['UN']
        : t.stopTimes[stationCode];
      const diff = (timeToMinutes(arrival) - timeToMinutes(departure) + 1440) % 1440;
      return {
        departure,
        arrival,
        tripTime: `${diff} min`,
        vehicleType: t.vehicleType,
        tripId: t.tripId,
        stopTimes: t.stopTimes,
      };
    });
}

// ── Stop sequence ─────────────────────────────────────────

export interface StationStop {
  name: string;
  code: string;
  scheduledTime: string;    // "HH:MM"
  scheduledMinutes: number; // absolute minutes from midnight
}

/**
 * Returns the ordered stop sequence for a trip using exact GTFS stop times.
 * Works for any station on the Stouffville line.
 */
export function getStops(
  trip: Trip,
  direction: Direction,
  homeCode: string = 'UI',
  liveStops?: string[],
): StationStop[] {
  const order = direction === 'homeToOffice' ? SB_ORDER : NB_ORDER;
  const stopTimes = trip.stopTimes;

  // Build list of stops that this trip actually serves, in correct order
  const tripStopCodes = order.filter((code) => code in stopTimes);

  // For SB: include from homeCode onward to UN (or trip terminus)
  // For NB: include from UN onward up to homeCode (or trip terminus)
  let relevantCodes: string[];
  if (direction === 'homeToOffice') {
    const homeIdx = tripStopCodes.indexOf(homeCode);
    relevantCodes = homeIdx >= 0 ? tripStopCodes.slice(homeIdx) : tripStopCodes;
  } else {
    const homeIdx = tripStopCodes.indexOf(homeCode);
    relevantCodes = homeIdx >= 0 ? tripStopCodes.slice(0, homeIdx + 1) : tripStopCodes;
  }

  if (liveStops && liveStops.length > 0) {
    return applyLiveStops(relevantCodes, stopTimes, liveStops, trip.departure, direction);
  }

  return relevantCodes.map((code) => {
    const time = stopTimes[code];
    const mins = timeToMinutes(time);
    return { name: STOP_NAMES[code] ?? code, code, scheduledTime: time, scheduledMinutes: mins };
  });
}

/**
 * Merges railsix live stop names into the computed stop sequence.
 * Uses GTFS times for any stop we recognize; falls back to interpolation otherwise.
 */
function applyLiveStops(
  staticCodes: string[],
  stopTimes: Record<string, string>,
  liveStops: string[],
  _tripDeparture: string,
  direction: Direction,
): StationStop[] {
  const origin = staticCodes[0];
  const dest = staticCodes[staticCodes.length - 1];
  const destName = (STOP_NAMES[dest] ?? dest).toLowerCase().replace(/ go$/, '').trim();

  const destIdx = liveStops.findIndex(
    (s) => s.toLowerCase().replace(/ go$/, '').trim() === destName || s.toLowerCase().includes(destName),
  );
  const relevant = destIdx >= 0 ? liveStops.slice(0, destIdx + 1) : liveStops;

  const merged: string[] = direction === 'homeToOffice'
    ? [origin, ...relevant.map((s) => STOP_CODE_MAP[s.toLowerCase().replace(/ go$/, '').trim()] ?? s)]
    : [...relevant.map((s) => STOP_CODE_MAP[s.toLowerCase().replace(/ go$/, '').trim()] ?? s), dest];

  // Deduplicate while preserving order
  const seen = new Set<string>();
  const deduped = merged.filter((c) => { if (seen.has(c)) return false; seen.add(c); return true; });

  return deduped.map((code) => {
    const time = stopTimes[code] ?? '';
    const mins = time ? timeToMinutes(time) : 0;
    return {
      name: STOP_NAMES[code] ?? code,
      code,
      scheduledTime: time,
      scheduledMinutes: mins,
    };
  });
}

// ── Helpers ───────────────────────────────────────────────

export function getServiceType(date: Date): ServiceType {
  const day = date.getDay();
  if (day === 0) return 'sunday';
  if (day === 6) return 'saturday';
  return 'weekday';
}

/** Convert "HH:MM" to total minutes from midnight */
export function timeToMinutes(time: string): number {
  const [h, m] = time.split(':').map(Number);
  return h * 60 + m;
}

export function minutesToTime(totalMinutes: number): string {
  const wrapped = ((totalMinutes % 1440) + 1440) % 1440;
  const h = Math.floor(wrapped / 60);
  const m = wrapped % 60;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}
